let unary = !ready || ~mask;
let contextual = typeof value === "string" && void effect() === undefined;
delete target.old;
let signed = +positive - -negative;
let power = 2 ** 3 ** 2;
let arithmetic = (a * b / c) % d + e - f;
let shifted = ((value << 2) >> 1) >>> 1;
let compared = a < b && b <= c && c > d && d >= e;
let equality = a == b || a != c || a === d || a !== e;
let bits = (left & right) ^ (left | right);
let selected = input ?? fallback ? left : right;
target = source;
target += 1;
target -= 1;
target *= 2;
target /= 2;
target %= 2;
target <<= 1;
target >>= 1;
target **= 2;
target >>>= 1;
target &= mask;
target ^= mask;
target |= mask;
target ??= fallback;
