#!/usr/bin/env python3
"""Generate ECMAScript identifier property tables from Unicode 17.0.0."""

from pathlib import Path
from urllib.request import urlopen

UNICODE_VERSION = "17.0.0"
SOURCE_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/DerivedCoreProperties.txt"
OUTPUT = Path(__file__).resolve().parents[1] / "src/frontend/unicode_identifiers.zig"


def ranges_for(text: str, property_name: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for raw_line in text.splitlines():
        data, _, _comment = raw_line.partition("#")
        fields = [field.strip() for field in data.split(";")]
        if len(fields) < 2 or fields[1] != property_name:
            continue
        bounds = fields[0].split("..")
        start = int(bounds[0], 16)
        end = int(bounds[-1], 16)
        ranges.append((start, end))
    return ranges


def emit_table(name: str, ranges: list[tuple[int, int]]) -> str:
    rows = "\n".join(
        f"    .{{ .first = 0x{start:X}, .last = 0x{end:X} }},"
        for start, end in ranges
    )
    return f"const {name} = [_]Range{{\n{rows}\n}};"


def main() -> None:
    with urlopen(SOURCE_URL) as response:
        source = response.read().decode("utf-8")

    id_start = ranges_for(source, "ID_Start")
    id_continue = ranges_for(source, "ID_Continue")
    if not id_start or not id_continue:
        raise RuntimeError("Unicode property tables were not found")

    output = f'''// Generated by tools/generate_unicode_identifiers.py from:
// {SOURCE_URL}
// Do not edit manually.

const Range = struct {{ first: u21, last: u21 }};

pub const unicode_version = "{UNICODE_VERSION}";

pub fn isIdStart(code_point: u21) bool {{
    return contains(&id_start_ranges, code_point);
}}

pub fn isIdContinue(code_point: u21) bool {{
    return contains(&id_continue_ranges, code_point);
}}

fn contains(ranges: []const Range, code_point: u21) bool {{
    var low: usize = 0;
    var high: usize = ranges.len;
    while (low < high) {{
        const middle = low + (high - low) / 2;
        const range = ranges[middle];
        if (code_point < range.first) {{
            high = middle;
        }} else if (code_point > range.last) {{
            low = middle + 1;
        }} else {{
            return true;
        }}
    }}
    return false;
}}

{emit_table("id_start_ranges", id_start)}

{emit_table("id_continue_ranges", id_continue)}
'''
    OUTPUT.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
