const std = @import("std");
const abi = @import("vizg-abi");

extern fn vizg_c_sizeof_Vizg_ProjectStatus() usize;
extern fn vizg_c_alignof_Vizg_ProjectStatus() usize;
extern fn vizg_c_sizeof_Vizg_LimitKind() usize;
extern fn vizg_c_alignof_Vizg_LimitKind() usize;
extern fn vizg_c_sizeof_Vizg_ProjectSourceKind() usize;
extern fn vizg_c_alignof_Vizg_ProjectSourceKind() usize;
extern fn vizg_c_sizeof_Vizg_ProjectStepKind() usize;
extern fn vizg_c_alignof_Vizg_ProjectStepKind() usize;
extern fn vizg_c_sizeof_Vizg_ProjectRequestOperation() usize;
extern fn vizg_c_alignof_Vizg_ProjectRequestOperation() usize;
extern fn vizg_c_sizeof_Vizg_ProjectFailureKind() usize;
extern fn vizg_c_alignof_Vizg_ProjectFailureKind() usize;
extern fn vizg_c_sizeof_Vizg_ExternalExportKind() usize;
extern fn vizg_c_alignof_Vizg_ExternalExportKind() usize;
extern fn vizg_c_sizeof_Vizg_ExternalNamespaceFlags() usize;
extern fn vizg_c_alignof_Vizg_ExternalNamespaceFlags() usize;
extern fn vizg_c_sizeof_Vizg_ExternalType() usize;
extern fn vizg_c_alignof_Vizg_ExternalType() usize;
extern fn vizg_c_sizeof_Vizg_ExternalDeclarationKind() usize;
extern fn vizg_c_alignof_Vizg_ExternalDeclarationKind() usize;
extern fn vizg_c_sizeof_Vizg_ExternalEffectFlags() usize;
extern fn vizg_c_alignof_Vizg_ExternalEffectFlags() usize;
extern fn vizg_c_sizeof_Vizg_HirEntityKind() usize;
extern fn vizg_c_alignof_Vizg_HirEntityKind() usize;
extern fn vizg_c_sizeof_Vizg_ProjectConfig() usize;
extern fn vizg_c_alignof_Vizg_ProjectConfig() usize;
extern fn vizg_c_sizeof_Vizg_ProjectSource() usize;
extern fn vizg_c_alignof_Vizg_ProjectSource() usize;
extern fn vizg_c_sizeof_Vizg_ProjectSpan() usize;
extern fn vizg_c_alignof_Vizg_ProjectSpan() usize;
extern fn vizg_c_sizeof_Vizg_ProjectRequestAttribute() usize;
extern fn vizg_c_alignof_Vizg_ProjectRequestAttribute() usize;
extern fn vizg_c_sizeof_Vizg_ProjectStep() usize;
extern fn vizg_c_alignof_Vizg_ProjectStep() usize;
extern fn vizg_c_sizeof_Vizg_ExternalExport() usize;
extern fn vizg_c_alignof_Vizg_ExternalExport() usize;
extern fn vizg_c_sizeof_Vizg_ExternalModule() usize;
extern fn vizg_c_alignof_Vizg_ExternalModule() usize;
extern fn vizg_c_sizeof_Vizg_ExternalParameterV2() usize;
extern fn vizg_c_alignof_Vizg_ExternalParameterV2() usize;
extern fn vizg_c_sizeof_Vizg_ExternalFunctionV2() usize;
extern fn vizg_c_alignof_Vizg_ExternalFunctionV2() usize;
extern fn vizg_c_sizeof_Vizg_ExternalExportV2() usize;
extern fn vizg_c_alignof_Vizg_ExternalExportV2() usize;
extern fn vizg_c_sizeof_Vizg_ExternalModuleV2() usize;
extern fn vizg_c_alignof_Vizg_ExternalModuleV2() usize;
extern fn vizg_c_sizeof_Vizg_SourceHostBinding() usize;
extern fn vizg_c_alignof_Vizg_SourceHostBinding() usize;
extern fn vizg_c_sizeof_Vizg_AmbientGlobal() usize;
extern fn vizg_c_alignof_Vizg_AmbientGlobal() usize;
extern fn vizg_c_sizeof_Vizg_AmbientMember() usize;
extern fn vizg_c_alignof_Vizg_AmbientMember() usize;
extern fn vizg_c_sizeof_Vizg_AmbientGlobalV2() usize;
extern fn vizg_c_alignof_Vizg_AmbientGlobalV2() usize;
extern fn vizg_c_sizeof_Vizg_ProjectResultSummary() usize;
extern fn vizg_c_sizeof_Vizg_ProjectModuleInfo() usize;
extern fn vizg_c_sizeof_Vizg_ProjectDiagnostic() usize;
extern fn vizg_c_sizeof_Vizg_ProjectEdgeInfo() usize;
extern fn vizg_c_sizeof_Vizg_ProjectImportInfo() usize;
extern fn vizg_c_sizeof_Vizg_ProjectExportInfo() usize;
extern fn vizg_c_alignof_Vizg_ProjectResultSummary() usize;
extern fn vizg_c_alignof_Vizg_ProjectModuleInfo() usize;
extern fn vizg_c_alignof_Vizg_ProjectDiagnostic() usize;
extern fn vizg_c_alignof_Vizg_ProjectEdgeInfo() usize;
extern fn vizg_c_alignof_Vizg_ProjectImportInfo() usize;
extern fn vizg_c_alignof_Vizg_ProjectExportInfo() usize;
extern fn vizg_c_sizeof_Vizg_HirSummary() usize;
extern fn vizg_c_alignof_Vizg_HirSummary() usize;
extern fn vizg_c_sizeof_Vizg_HirRecord() usize;
extern fn vizg_c_alignof_Vizg_HirRecord() usize;
extern fn vizg_c_sizeof_Vizg_HirPayload() usize;
extern fn vizg_c_alignof_Vizg_HirPayload() usize;
extern fn vizg_c_sizeof_Vizg_HirPayloadItem() usize;
extern fn vizg_c_alignof_Vizg_HirPayloadItem() usize;
extern fn vizg_c_sizeof_Vizg_HirTypeDetail() usize;
extern fn vizg_c_alignof_Vizg_HirTypeDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirFunctionSignature() usize;
extern fn vizg_c_alignof_Vizg_HirFunctionSignature() usize;
extern fn vizg_c_sizeof_Vizg_HirSignatureParameter() usize;
extern fn vizg_c_alignof_Vizg_HirSignatureParameter() usize;
extern fn vizg_c_sizeof_Vizg_HirFunctionDetail() usize;
extern fn vizg_c_alignof_Vizg_HirFunctionDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirFunctionParameter() usize;
extern fn vizg_c_alignof_Vizg_HirFunctionParameter() usize;
extern fn vizg_c_sizeof_Vizg_HirBlockDetail() usize;
extern fn vizg_c_alignof_Vizg_HirBlockDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirBlockParameter() usize;
extern fn vizg_c_alignof_Vizg_HirBlockParameter() usize;
extern fn vizg_c_sizeof_Vizg_HirOriginDetail() usize;
extern fn vizg_c_alignof_Vizg_HirOriginDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirSemanticIdentity() usize;
extern fn vizg_c_alignof_Vizg_HirSemanticIdentity() usize;
extern fn vizg_c_sizeof_Vizg_HirModuleDetail() usize;
extern fn vizg_c_alignof_Vizg_HirModuleDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirModuleDependency() usize;
extern fn vizg_c_alignof_Vizg_HirModuleDependency() usize;
extern fn vizg_c_sizeof_Vizg_HirModuleImport() usize;
extern fn vizg_c_alignof_Vizg_HirModuleImport() usize;
extern fn vizg_c_sizeof_Vizg_HirModuleExport() usize;
extern fn vizg_c_alignof_Vizg_HirModuleExport() usize;
extern fn vizg_c_sizeof_Vizg_HirBindingDetail() usize;
extern fn vizg_c_alignof_Vizg_HirBindingDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirFunctionStorageDetail() usize;
extern fn vizg_c_alignof_Vizg_HirFunctionStorageDetail() usize;
extern fn vizg_c_sizeof_Vizg_HirFunctionCapture() usize;
extern fn vizg_c_alignof_Vizg_HirFunctionCapture() usize;
extern fn vizg_c_sizeof_Vizg_HirRegionDetail() usize;
extern fn vizg_c_alignof_Vizg_HirRegionDetail() usize;
extern fn vizg_c_fields_Vizg_ProjectConfig() usize;
extern fn vizg_c_fields_Vizg_ProjectSource() usize;
extern fn vizg_c_fields_Vizg_ProjectSpan() usize;
extern fn vizg_c_fields_Vizg_ProjectRequestAttribute() usize;
extern fn vizg_c_fields_Vizg_ProjectStep() usize;
extern fn vizg_c_fields_Vizg_ExternalExport() usize;
extern fn vizg_c_fields_Vizg_ExternalModule() usize;
extern fn vizg_c_fields_Vizg_ExternalParameterV2() usize;
extern fn vizg_c_fields_Vizg_ExternalFunctionV2() usize;
extern fn vizg_c_fields_Vizg_ExternalExportV2() usize;
extern fn vizg_c_fields_Vizg_ExternalModuleV2() usize;
extern fn vizg_c_fields_Vizg_SourceHostBinding() usize;
extern fn vizg_c_fields_Vizg_AmbientGlobal() usize;
extern fn vizg_c_fields_Vizg_AmbientMember() usize;
extern fn vizg_c_fields_Vizg_AmbientGlobalV2() usize;
extern fn vizg_c_fields_Vizg_ProjectResultSummary() usize;
extern fn vizg_c_fields_Vizg_ProjectDiagnostic() usize;
extern fn vizg_c_fields_Vizg_ProjectEdgeInfo() usize;
extern fn vizg_c_fields_Vizg_ProjectImportInfo() usize;
extern fn vizg_c_fields_Vizg_ProjectExportInfo() usize;
extern fn vizg_c_fields_Vizg_HirSummary() usize;
extern fn vizg_c_fields_Vizg_HirRecord() usize;
extern fn vizg_c_fields_Vizg_HirPayload() usize;
extern fn vizg_c_fields_Vizg_HirPayloadItem() usize;
extern fn vizg_c_fields_Vizg_HirTypeDetail() usize;
extern fn vizg_c_fields_Vizg_HirFunctionSignature() usize;
extern fn vizg_c_fields_Vizg_HirSignatureParameter() usize;
extern fn vizg_c_fields_Vizg_HirFunctionDetail() usize;
extern fn vizg_c_fields_Vizg_HirFunctionParameter() usize;
extern fn vizg_c_fields_Vizg_HirBlockDetail() usize;
extern fn vizg_c_fields_Vizg_HirBlockParameter() usize;
extern fn vizg_c_fields_Vizg_HirOriginDetail() usize;
extern fn vizg_c_fields_Vizg_HirSemanticIdentity() usize;
extern fn vizg_c_fields_Vizg_HirModuleDetail() usize;
extern fn vizg_c_fields_Vizg_HirModuleDependency() usize;
extern fn vizg_c_fields_Vizg_HirModuleImport() usize;
extern fn vizg_c_fields_Vizg_HirModuleExport() usize;
extern fn vizg_c_fields_Vizg_HirBindingDetail() usize;
extern fn vizg_c_fields_Vizg_HirFunctionStorageDetail() usize;
extern fn vizg_c_fields_Vizg_HirFunctionCapture() usize;
extern fn vizg_c_fields_Vizg_HirRegionDetail() usize;
extern fn vizg_c_value_project_status_internal_error() u32;
extern fn vizg_c_value_limit_semantic_growth() u32;
extern fn vizg_c_value_limit_parse_depth() u32;
extern fn vizg_c_value_project_request_re_export() u32;
extern fn vizg_c_value_external_type_object() u32;
extern fn vizg_c_value_external_namespace_value() u8;
extern fn vizg_c_value_external_namespace_type() u8;
extern fn vizg_c_value_external_namespace_both() u8;
extern fn vizg_c_value_external_module_api_version() u32;
extern fn vizg_c_value_external_declaration_type() u32;
extern fn vizg_c_value_external_effect_unknown() u16;

fn expectLayout(comptime T: type, size: usize, alignment: usize) !void {
    try std.testing.expectEqual(@sizeOf(T), size);
    try std.testing.expectEqual(@alignOf(T), alignment);
}
fn f(comptime T: type, comptime field: []const u8, weight: usize) usize {
    return @offsetOf(T, field) * weight;
}

test "official ABI v1 C and Zig layouts match" {
    try expectLayout(abi.Vizg_ProjectStatus, vizg_c_sizeof_Vizg_ProjectStatus(), vizg_c_alignof_Vizg_ProjectStatus());
    try expectLayout(abi.Vizg_LimitKind, vizg_c_sizeof_Vizg_LimitKind(), vizg_c_alignof_Vizg_LimitKind());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ProjectSourceKind(), vizg_c_alignof_Vizg_ProjectSourceKind());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ProjectStepKind(), vizg_c_alignof_Vizg_ProjectStepKind());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ProjectRequestOperation(), vizg_c_alignof_Vizg_ProjectRequestOperation());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ProjectFailureKind(), vizg_c_alignof_Vizg_ProjectFailureKind());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ExternalExportKind(), vizg_c_alignof_Vizg_ExternalExportKind());
    try expectLayout(abi.Vizg_ExternalNamespaceFlags, vizg_c_sizeof_Vizg_ExternalNamespaceFlags(), vizg_c_alignof_Vizg_ExternalNamespaceFlags());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ExternalType(), vizg_c_alignof_Vizg_ExternalType());
    try expectLayout(u32, vizg_c_sizeof_Vizg_ExternalDeclarationKind(), vizg_c_alignof_Vizg_ExternalDeclarationKind());
    try expectLayout(u16, vizg_c_sizeof_Vizg_ExternalEffectFlags(), vizg_c_alignof_Vizg_ExternalEffectFlags());
    try expectLayout(u32, vizg_c_sizeof_Vizg_HirEntityKind(), vizg_c_alignof_Vizg_HirEntityKind());
    try expectLayout(abi.Vizg_ProjectConfig, vizg_c_sizeof_Vizg_ProjectConfig(), vizg_c_alignof_Vizg_ProjectConfig());
    try expectLayout(abi.Vizg_ProjectSource, vizg_c_sizeof_Vizg_ProjectSource(), vizg_c_alignof_Vizg_ProjectSource());
    try expectLayout(abi.Vizg_ProjectSpan, vizg_c_sizeof_Vizg_ProjectSpan(), vizg_c_alignof_Vizg_ProjectSpan());
    try expectLayout(abi.Vizg_ProjectRequestAttribute, vizg_c_sizeof_Vizg_ProjectRequestAttribute(), vizg_c_alignof_Vizg_ProjectRequestAttribute());
    try expectLayout(abi.Vizg_ProjectStep, vizg_c_sizeof_Vizg_ProjectStep(), vizg_c_alignof_Vizg_ProjectStep());
    try expectLayout(abi.Vizg_ExternalExport, vizg_c_sizeof_Vizg_ExternalExport(), vizg_c_alignof_Vizg_ExternalExport());
    try expectLayout(abi.Vizg_ExternalModule, vizg_c_sizeof_Vizg_ExternalModule(), vizg_c_alignof_Vizg_ExternalModule());
    try expectLayout(abi.Vizg_ExternalParameterV2, vizg_c_sizeof_Vizg_ExternalParameterV2(), vizg_c_alignof_Vizg_ExternalParameterV2());
    try expectLayout(abi.Vizg_ExternalFunctionV2, vizg_c_sizeof_Vizg_ExternalFunctionV2(), vizg_c_alignof_Vizg_ExternalFunctionV2());
    try expectLayout(abi.Vizg_ExternalExportV2, vizg_c_sizeof_Vizg_ExternalExportV2(), vizg_c_alignof_Vizg_ExternalExportV2());
    try expectLayout(abi.Vizg_ExternalModuleV2, vizg_c_sizeof_Vizg_ExternalModuleV2(), vizg_c_alignof_Vizg_ExternalModuleV2());
    try expectLayout(abi.Vizg_SourceHostBinding, vizg_c_sizeof_Vizg_SourceHostBinding(), vizg_c_alignof_Vizg_SourceHostBinding());
    try expectLayout(abi.Vizg_AmbientGlobal, vizg_c_sizeof_Vizg_AmbientGlobal(), vizg_c_alignof_Vizg_AmbientGlobal());
    try expectLayout(abi.Vizg_AmbientMember, vizg_c_sizeof_Vizg_AmbientMember(), vizg_c_alignof_Vizg_AmbientMember());
    try expectLayout(abi.Vizg_AmbientGlobalV2, vizg_c_sizeof_Vizg_AmbientGlobalV2(), vizg_c_alignof_Vizg_AmbientGlobalV2());
    try expectLayout(abi.Vizg_ProjectResultSummary, vizg_c_sizeof_Vizg_ProjectResultSummary(), vizg_c_alignof_Vizg_ProjectResultSummary());
    try expectLayout(abi.Vizg_ProjectModuleInfo, vizg_c_sizeof_Vizg_ProjectModuleInfo(), vizg_c_alignof_Vizg_ProjectModuleInfo());
    try expectLayout(abi.Vizg_ProjectDiagnostic, vizg_c_sizeof_Vizg_ProjectDiagnostic(), vizg_c_alignof_Vizg_ProjectDiagnostic());
    try expectLayout(abi.Vizg_ProjectEdgeInfo, vizg_c_sizeof_Vizg_ProjectEdgeInfo(), vizg_c_alignof_Vizg_ProjectEdgeInfo());
    try expectLayout(abi.Vizg_ProjectImportInfo, vizg_c_sizeof_Vizg_ProjectImportInfo(), vizg_c_alignof_Vizg_ProjectImportInfo());
    try expectLayout(abi.Vizg_ProjectExportInfo, vizg_c_sizeof_Vizg_ProjectExportInfo(), vizg_c_alignof_Vizg_ProjectExportInfo());
    try expectLayout(abi.Vizg_HirSummary, vizg_c_sizeof_Vizg_HirSummary(), vizg_c_alignof_Vizg_HirSummary());
    try expectLayout(abi.Vizg_HirRecord, vizg_c_sizeof_Vizg_HirRecord(), vizg_c_alignof_Vizg_HirRecord());
    try expectLayout(abi.Vizg_HirPayload, vizg_c_sizeof_Vizg_HirPayload(), vizg_c_alignof_Vizg_HirPayload());
    try expectLayout(abi.Vizg_HirPayloadItem, vizg_c_sizeof_Vizg_HirPayloadItem(), vizg_c_alignof_Vizg_HirPayloadItem());
    try expectLayout(abi.Vizg_HirTypeDetail, vizg_c_sizeof_Vizg_HirTypeDetail(), vizg_c_alignof_Vizg_HirTypeDetail());
    try expectLayout(abi.Vizg_HirFunctionSignature, vizg_c_sizeof_Vizg_HirFunctionSignature(), vizg_c_alignof_Vizg_HirFunctionSignature());
    try expectLayout(abi.Vizg_HirSignatureParameter, vizg_c_sizeof_Vizg_HirSignatureParameter(), vizg_c_alignof_Vizg_HirSignatureParameter());
    try expectLayout(abi.Vizg_HirFunctionDetail, vizg_c_sizeof_Vizg_HirFunctionDetail(), vizg_c_alignof_Vizg_HirFunctionDetail());
    try expectLayout(abi.Vizg_HirFunctionParameter, vizg_c_sizeof_Vizg_HirFunctionParameter(), vizg_c_alignof_Vizg_HirFunctionParameter());
    try expectLayout(abi.Vizg_HirBlockDetail, vizg_c_sizeof_Vizg_HirBlockDetail(), vizg_c_alignof_Vizg_HirBlockDetail());
    try expectLayout(abi.Vizg_HirBlockParameter, vizg_c_sizeof_Vizg_HirBlockParameter(), vizg_c_alignof_Vizg_HirBlockParameter());
    try expectLayout(abi.Vizg_HirOriginDetail, vizg_c_sizeof_Vizg_HirOriginDetail(), vizg_c_alignof_Vizg_HirOriginDetail());
    try expectLayout(abi.Vizg_HirSemanticIdentity, vizg_c_sizeof_Vizg_HirSemanticIdentity(), vizg_c_alignof_Vizg_HirSemanticIdentity());
    try expectLayout(abi.Vizg_HirModuleDetail, vizg_c_sizeof_Vizg_HirModuleDetail(), vizg_c_alignof_Vizg_HirModuleDetail());
    try expectLayout(abi.Vizg_HirModuleDependency, vizg_c_sizeof_Vizg_HirModuleDependency(), vizg_c_alignof_Vizg_HirModuleDependency());
    try expectLayout(abi.Vizg_HirModuleImport, vizg_c_sizeof_Vizg_HirModuleImport(), vizg_c_alignof_Vizg_HirModuleImport());
    try expectLayout(abi.Vizg_HirModuleExport, vizg_c_sizeof_Vizg_HirModuleExport(), vizg_c_alignof_Vizg_HirModuleExport());
    try expectLayout(abi.Vizg_HirBindingDetail, vizg_c_sizeof_Vizg_HirBindingDetail(), vizg_c_alignof_Vizg_HirBindingDetail());
    try expectLayout(abi.Vizg_HirFunctionStorageDetail, vizg_c_sizeof_Vizg_HirFunctionStorageDetail(), vizg_c_alignof_Vizg_HirFunctionStorageDetail());
    try expectLayout(abi.Vizg_HirFunctionCapture, vizg_c_sizeof_Vizg_HirFunctionCapture(), vizg_c_alignof_Vizg_HirFunctionCapture());
    try expectLayout(abi.Vizg_HirRegionDetail, vizg_c_sizeof_Vizg_HirRegionDetail(), vizg_c_alignof_Vizg_HirRegionDetail());

    try std.testing.expectEqual(f(abi.Vizg_ProjectConfig, "workspace_ptr", 1) + f(abi.Vizg_ProjectConfig, "workspace_len", 2) + f(abi.Vizg_ProjectConfig, "max_source_bytes", 3) + f(abi.Vizg_ProjectConfig, "max_total_source_bytes", 4) + f(abi.Vizg_ProjectConfig, "max_modules", 5) + f(abi.Vizg_ProjectConfig, "max_requests", 6) + f(abi.Vizg_ProjectConfig, "max_edges", 7) + f(abi.Vizg_ProjectConfig, "max_diagnostics", 8) + f(abi.Vizg_ProjectConfig, "max_graph_depth", 9) + f(abi.Vizg_ProjectConfig, "max_semantic_types", 10), vizg_c_fields_Vizg_ProjectConfig());
    try std.testing.expectEqual(f(abi.Vizg_ProjectSource, "module_id", 1) + f(abi.Vizg_ProjectSource, "logical_name_ptr", 2) + f(abi.Vizg_ProjectSource, "logical_name_len", 3) + f(abi.Vizg_ProjectSource, "source_ptr", 4) + f(abi.Vizg_ProjectSource, "source_len", 5) + f(abi.Vizg_ProjectSource, "kind", 6) + f(abi.Vizg_ProjectSource, "is_root", 7) + f(abi.Vizg_ProjectSource, "reserved", 8), vizg_c_fields_Vizg_ProjectSource());
    try std.testing.expectEqual(f(abi.Vizg_ProjectSpan, "start", 1) + f(abi.Vizg_ProjectSpan, "end", 2) + f(abi.Vizg_ProjectSpan, "line", 3) + f(abi.Vizg_ProjectSpan, "column", 4), vizg_c_fields_Vizg_ProjectSpan());
    try std.testing.expectEqual(f(abi.Vizg_ProjectRequestAttribute, "key_ptr", 1) + f(abi.Vizg_ProjectRequestAttribute, "key_len", 2) + f(abi.Vizg_ProjectRequestAttribute, "value_ptr", 3) + f(abi.Vizg_ProjectRequestAttribute, "value_len", 4) + f(abi.Vizg_ProjectRequestAttribute, "span", 5), vizg_c_fields_Vizg_ProjectRequestAttribute());
    try std.testing.expectEqual(f(abi.Vizg_ProjectStep, "kind", 1) + f(abi.Vizg_ProjectStep, "request_id", 2) + f(abi.Vizg_ProjectStep, "importer_module_id", 3) + f(abi.Vizg_ProjectStep, "specifier_ptr", 4) + f(abi.Vizg_ProjectStep, "specifier_len", 5) + f(abi.Vizg_ProjectStep, "request_operation", 6) + f(abi.Vizg_ProjectStep, "type_only", 7) + f(abi.Vizg_ProjectStep, "reserved", 8) + f(abi.Vizg_ProjectStep, "attributes_ptr", 9) + f(abi.Vizg_ProjectStep, "attribute_count", 10) + f(abi.Vizg_ProjectStep, "span", 11), vizg_c_fields_Vizg_ProjectStep());
    try std.testing.expectEqual(f(abi.Vizg_ExternalExport, "name_ptr", 1) + f(abi.Vizg_ExternalExport, "name_len", 2) + f(abi.Vizg_ExternalExport, "kind", 3) + f(abi.Vizg_ExternalExport, "namespace_flags", 4) + f(abi.Vizg_ExternalExport, "has_type_metadata", 5) + f(abi.Vizg_ExternalExport, "reserved", 6) + f(abi.Vizg_ExternalExport, "type_metadata", 7), vizg_c_fields_Vizg_ExternalExport());
    try std.testing.expectEqual(f(abi.Vizg_ExternalModule, "external_module_id", 1) + f(abi.Vizg_ExternalModule, "logical_name_ptr", 2) + f(abi.Vizg_ExternalModule, "logical_name_len", 3) + f(abi.Vizg_ExternalModule, "exports_ptr", 4) + f(abi.Vizg_ExternalModule, "export_count", 5), vizg_c_fields_Vizg_ExternalModule());
    try std.testing.expectEqual(f(abi.Vizg_ExternalParameterV2, "name_ptr", 1) + f(abi.Vizg_ExternalParameterV2, "name_len", 2) + f(abi.Vizg_ExternalParameterV2, "type_metadata", 3) + f(abi.Vizg_ExternalParameterV2, "optional", 4) + f(abi.Vizg_ExternalParameterV2, "has_default", 5) + f(abi.Vizg_ExternalParameterV2, "rest", 6) + f(abi.Vizg_ExternalParameterV2, "reserved", 7), vizg_c_fields_Vizg_ExternalParameterV2());
    try std.testing.expectEqual(f(abi.Vizg_ExternalFunctionV2, "parameters_ptr", 1) + f(abi.Vizg_ExternalFunctionV2, "parameter_count", 2) + f(abi.Vizg_ExternalFunctionV2, "return_type", 3) + f(abi.Vizg_ExternalFunctionV2, "type_parameter_count", 4) + f(abi.Vizg_ExternalFunctionV2, "is_async", 5) + f(abi.Vizg_ExternalFunctionV2, "is_generator", 6) + f(abi.Vizg_ExternalFunctionV2, "is_constructor", 7) + f(abi.Vizg_ExternalFunctionV2, "reserved", 8), vizg_c_fields_Vizg_ExternalFunctionV2());
    try std.testing.expectEqual(f(abi.Vizg_ExternalExportV2, "name_ptr", 1) + f(abi.Vizg_ExternalExportV2, "name_len", 2) + f(abi.Vizg_ExternalExportV2, "kind", 3) + f(abi.Vizg_ExternalExportV2, "namespace_flags", 4) + f(abi.Vizg_ExternalExportV2, "has_type_metadata", 5) + f(abi.Vizg_ExternalExportV2, "has_function", 6) + f(abi.Vizg_ExternalExportV2, "reserved", 7) + f(abi.Vizg_ExternalExportV2, "type_metadata", 8) + f(abi.Vizg_ExternalExportV2, "declaration_kind", 9) + f(abi.Vizg_ExternalExportV2, "effect_flags", 10) + f(abi.Vizg_ExternalExportV2, "reserved2", 11) + f(abi.Vizg_ExternalExportV2, "external_symbol_id", 12) + f(abi.Vizg_ExternalExportV2, "function", 13), vizg_c_fields_Vizg_ExternalExportV2());
    try std.testing.expectEqual(f(abi.Vizg_ExternalModuleV2, "external_module_id", 1) + f(abi.Vizg_ExternalModuleV2, "logical_name_ptr", 2) + f(abi.Vizg_ExternalModuleV2, "logical_name_len", 3) + f(abi.Vizg_ExternalModuleV2, "exports_ptr", 4) + f(abi.Vizg_ExternalModuleV2, "export_count", 5), vizg_c_fields_Vizg_ExternalModuleV2());
    try std.testing.expectEqual(f(abi.Vizg_SourceHostBinding, "name_ptr", 1) + f(abi.Vizg_SourceHostBinding, "name_len", 2) + f(abi.Vizg_SourceHostBinding, "host_binding_id", 3) + f(abi.Vizg_SourceHostBinding, "reserved", 4), vizg_c_fields_Vizg_SourceHostBinding());
    try std.testing.expectEqual(f(abi.Vizg_AmbientGlobal, "name_ptr", 1) + f(abi.Vizg_AmbientGlobal, "name_len", 2) + f(abi.Vizg_AmbientGlobal, "namespace_flags", 3) + f(abi.Vizg_AmbientGlobal, "has_type_metadata", 4) + f(abi.Vizg_AmbientGlobal, "type_metadata", 5) + f(abi.Vizg_AmbientGlobal, "host_binding_id", 6) + f(abi.Vizg_AmbientGlobal, "reserved", 7), vizg_c_fields_Vizg_AmbientGlobal());
    try std.testing.expectEqual(f(abi.Vizg_AmbientMember, "name_ptr", 1) + f(abi.Vizg_AmbientMember, "name_len", 2) + f(abi.Vizg_AmbientMember, "has_type_metadata", 3) + f(abi.Vizg_AmbientMember, "optional", 4) + f(abi.Vizg_AmbientMember, "readonly", 5) + f(abi.Vizg_AmbientMember, "self_reference", 6) + f(abi.Vizg_AmbientMember, "type_metadata", 7) + f(abi.Vizg_AmbientMember, "reserved", 8), vizg_c_fields_Vizg_AmbientMember());
    try std.testing.expectEqual(f(abi.Vizg_AmbientGlobalV2, "name_ptr", 1) + f(abi.Vizg_AmbientGlobalV2, "name_len", 2) + f(abi.Vizg_AmbientGlobalV2, "namespace_flags", 3) + f(abi.Vizg_AmbientGlobalV2, "has_type_metadata", 4) + f(abi.Vizg_AmbientGlobalV2, "type_metadata", 5) + f(abi.Vizg_AmbientGlobalV2, "host_binding_id", 6) + f(abi.Vizg_AmbientGlobalV2, "members_ptr", 7) + f(abi.Vizg_AmbientGlobalV2, "member_count", 8) + f(abi.Vizg_AmbientGlobalV2, "reserved", 9), vizg_c_fields_Vizg_AmbientGlobalV2());
    try std.testing.expectEqual(f(abi.Vizg_ProjectResultSummary, "module_count", 1) + f(abi.Vizg_ProjectResultSummary, "diagnostic_count", 2) + f(abi.Vizg_ProjectResultSummary, "edge_count", 3) + f(abi.Vizg_ProjectResultSummary, "import_count", 4) + f(abi.Vizg_ProjectResultSummary, "export_count", 5) + f(abi.Vizg_ProjectResultSummary, "is_partial", 6) + f(abi.Vizg_ProjectResultSummary, "has_syntax_errors", 7) + f(abi.Vizg_ProjectResultSummary, "has_semantic_errors", 8) + f(abi.Vizg_ProjectResultSummary, "has_project_errors", 9) + f(abi.Vizg_ProjectResultSummary, "has_module_failures", 10) + f(abi.Vizg_ProjectResultSummary, "reserved", 11), vizg_c_fields_Vizg_ProjectResultSummary());
    try std.testing.expectEqual(f(abi.Vizg_ProjectDiagnostic, "module_id", 1) + f(abi.Vizg_ProjectDiagnostic, "has_module_id", 2) + f(abi.Vizg_ProjectDiagnostic, "severity", 3) + f(abi.Vizg_ProjectDiagnostic, "phase", 4) + f(abi.Vizg_ProjectDiagnostic, "reserved", 5) + f(abi.Vizg_ProjectDiagnostic, "code", 6) + f(abi.Vizg_ProjectDiagnostic, "message_ptr", 7) + f(abi.Vizg_ProjectDiagnostic, "message_len", 8) + f(abi.Vizg_ProjectDiagnostic, "logical_name_ptr", 9) + f(abi.Vizg_ProjectDiagnostic, "logical_name_len", 10) + f(abi.Vizg_ProjectDiagnostic, "span", 11), vizg_c_fields_Vizg_ProjectDiagnostic());
    try std.testing.expectEqual(f(abi.Vizg_ProjectEdgeInfo, "request_id", 1) + f(abi.Vizg_ProjectEdgeInfo, "importer_module_id", 2) + f(abi.Vizg_ProjectEdgeInfo, "target_module_id", 3) + f(abi.Vizg_ProjectEdgeInfo, "external_module_id", 4) + f(abi.Vizg_ProjectEdgeInfo, "specifier_ptr", 5) + f(abi.Vizg_ProjectEdgeInfo, "specifier_len", 6) + f(abi.Vizg_ProjectEdgeInfo, "request_operation", 7) + f(abi.Vizg_ProjectEdgeInfo, "state", 8) + f(abi.Vizg_ProjectEdgeInfo, "type_only", 9) + f(abi.Vizg_ProjectEdgeInfo, "has_target_module", 10) + f(abi.Vizg_ProjectEdgeInfo, "has_external_target", 11) + f(abi.Vizg_ProjectEdgeInfo, "reserved", 12) + f(abi.Vizg_ProjectEdgeInfo, "span", 13), vizg_c_fields_Vizg_ProjectEdgeInfo());
    try std.testing.expectEqual(f(abi.Vizg_ProjectImportInfo, "module_id", 1) + f(abi.Vizg_ProjectImportInfo, "target_module_id", 2) + f(abi.Vizg_ProjectImportInfo, "external_module_id", 3) + f(abi.Vizg_ProjectImportInfo, "edge_index", 4) + f(abi.Vizg_ProjectImportInfo, "target_type_id", 5) + f(abi.Vizg_ProjectImportInfo, "link_state", 6) + f(abi.Vizg_ProjectImportInfo, "request_operation", 7) + f(abi.Vizg_ProjectImportInfo, "local_name_ptr", 8) + f(abi.Vizg_ProjectImportInfo, "local_name_len", 9) + f(abi.Vizg_ProjectImportInfo, "imported_name_ptr", 10) + f(abi.Vizg_ProjectImportInfo, "imported_name_len", 11) + f(abi.Vizg_ProjectImportInfo, "specifier_ptr", 12) + f(abi.Vizg_ProjectImportInfo, "specifier_len", 13) + f(abi.Vizg_ProjectImportInfo, "type_only", 14) + f(abi.Vizg_ProjectImportInfo, "runtime_binding", 15) + f(abi.Vizg_ProjectImportInfo, "has_target_module", 16) + f(abi.Vizg_ProjectImportInfo, "has_external_target", 17) + f(abi.Vizg_ProjectImportInfo, "has_edge_index", 18) + f(abi.Vizg_ProjectImportInfo, "has_semantic_target", 19) + f(abi.Vizg_ProjectImportInfo, "reserved", 20) + f(abi.Vizg_ProjectImportInfo, "span", 21), vizg_c_fields_Vizg_ProjectImportInfo());
    try std.testing.expectEqual(f(abi.Vizg_ProjectExportInfo, "module_id", 1) + f(abi.Vizg_ProjectExportInfo, "target_module_id", 2) + f(abi.Vizg_ProjectExportInfo, "external_module_id", 3) + f(abi.Vizg_ProjectExportInfo, "edge_index", 4) + f(abi.Vizg_ProjectExportInfo, "target_type_id", 5) + f(abi.Vizg_ProjectExportInfo, "name_ptr", 6) + f(abi.Vizg_ProjectExportInfo, "name_len", 7) + f(abi.Vizg_ProjectExportInfo, "type_only", 8) + f(abi.Vizg_ProjectExportInfo, "re_export", 9) + f(abi.Vizg_ProjectExportInfo, "has_target_module", 10) + f(abi.Vizg_ProjectExportInfo, "has_external_target", 11) + f(abi.Vizg_ProjectExportInfo, "has_edge_index", 12) + f(abi.Vizg_ProjectExportInfo, "reserved", 13) + f(abi.Vizg_ProjectExportInfo, "span", 14), vizg_c_fields_Vizg_ProjectExportInfo());
    try std.testing.expectEqual(f(abi.Vizg_HirSummary, "module_count", 1) + f(abi.Vizg_HirSummary, "external_declaration_count", 2) + f(abi.Vizg_HirSummary, "function_count", 3) + f(abi.Vizg_HirSummary, "block_count", 4) + f(abi.Vizg_HirSummary, "instruction_count", 5) + f(abi.Vizg_HirSummary, "binding_count", 6) + f(abi.Vizg_HirSummary, "type_count", 7) + f(abi.Vizg_HirSummary, "origin_count", 8), vizg_c_fields_Vizg_HirSummary());
    try std.testing.expectEqual(f(abi.Vizg_HirRecord, "kind", 1) + f(abi.Vizg_HirRecord, "tag", 2) + f(abi.Vizg_HirRecord, "id", 3) + f(abi.Vizg_HirRecord, "parent_id", 4) + f(abi.Vizg_HirRecord, "secondary_id", 5) + f(abi.Vizg_HirRecord, "module_id", 6) + f(abi.Vizg_HirRecord, "type_id", 7) + f(abi.Vizg_HirRecord, "effect_bits", 8) + f(abi.Vizg_HirRecord, "flags", 9) + f(abi.Vizg_HirRecord, "reserved", 10) + f(abi.Vizg_HirRecord, "origin_id", 11) + f(abi.Vizg_HirRecord, "name_ptr", 12) + f(abi.Vizg_HirRecord, "name_len", 13) + f(abi.Vizg_HirRecord, "child_count", 14), vizg_c_fields_Vizg_HirRecord());
    try std.testing.expectEqual(f(abi.Vizg_HirPayload, "tag", 1) + f(abi.Vizg_HirPayload, "tag0", 2) + f(abi.Vizg_HirPayload, "tag1", 3) + f(abi.Vizg_HirPayload, "flags", 4) + f(abi.Vizg_HirPayload, "operand0", 5) + f(abi.Vizg_HirPayload, "operand1", 6) + f(abi.Vizg_HirPayload, "operand2", 7) + f(abi.Vizg_HirPayload, "operand3", 8) + f(abi.Vizg_HirPayload, "string0_ptr", 9) + f(abi.Vizg_HirPayload, "string0_len", 10) + f(abi.Vizg_HirPayload, "string1_ptr", 11) + f(abi.Vizg_HirPayload, "string1_len", 12) + f(abi.Vizg_HirPayload, "item_count", 13), vizg_c_fields_Vizg_HirPayload());
    try std.testing.expectEqual(f(abi.Vizg_HirPayloadItem, "tag", 1) + f(abi.Vizg_HirPayloadItem, "flags", 2) + f(abi.Vizg_HirPayloadItem, "operand0", 3) + f(abi.Vizg_HirPayloadItem, "operand1", 4) + f(abi.Vizg_HirPayloadItem, "string0_ptr", 5) + f(abi.Vizg_HirPayloadItem, "string0_len", 6) + f(abi.Vizg_HirPayloadItem, "string1_ptr", 7) + f(abi.Vizg_HirPayloadItem, "string1_len", 8), vizg_c_fields_Vizg_HirPayloadItem());
    try std.testing.expectEqual(f(abi.Vizg_HirTypeDetail, "id", 1) + f(abi.Vizg_HirTypeDetail, "kind", 2) + f(abi.Vizg_HirTypeDetail, "builtin_kind", 3) + f(abi.Vizg_HirTypeDetail, "reserved", 4), vizg_c_fields_Vizg_HirTypeDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirFunctionSignature, "type_id", 1) + f(abi.Vizg_HirFunctionSignature, "return_type_id", 2) + f(abi.Vizg_HirFunctionSignature, "type_parameter_count", 3) + f(abi.Vizg_HirFunctionSignature, "flags", 4) + f(abi.Vizg_HirFunctionSignature, "reserved", 5) + f(abi.Vizg_HirFunctionSignature, "parameter_count", 6), vizg_c_fields_Vizg_HirFunctionSignature());
    try std.testing.expectEqual(f(abi.Vizg_HirSignatureParameter, "name_ptr", 1) + f(abi.Vizg_HirSignatureParameter, "name_len", 2) + f(abi.Vizg_HirSignatureParameter, "type_id", 3) + f(abi.Vizg_HirSignatureParameter, "flags", 4) + f(abi.Vizg_HirSignatureParameter, "reserved", 5), vizg_c_fields_Vizg_HirSignatureParameter());
    try std.testing.expectEqual(f(abi.Vizg_HirFunctionDetail, "id", 1) + f(abi.Vizg_HirFunctionDetail, "entry_block_id", 2) + f(abi.Vizg_HirFunctionDetail, "parameter_count", 3) + f(abi.Vizg_HirFunctionDetail, "flags", 4) + f(abi.Vizg_HirFunctionDetail, "reserved", 5), vizg_c_fields_Vizg_HirFunctionDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirFunctionParameter, "binding_id", 1) + f(abi.Vizg_HirFunctionParameter, "type_id", 2) + f(abi.Vizg_HirFunctionParameter, "argument_index", 3) + f(abi.Vizg_HirFunctionParameter, "origin_id", 4) + f(abi.Vizg_HirFunctionParameter, "flags", 5) + f(abi.Vizg_HirFunctionParameter, "reserved", 6), vizg_c_fields_Vizg_HirFunctionParameter());
    try std.testing.expectEqual(f(abi.Vizg_HirBlockDetail, "id", 1) + f(abi.Vizg_HirBlockDetail, "parameter_count", 2), vizg_c_fields_Vizg_HirBlockDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirBlockParameter, "value_id", 1) + f(abi.Vizg_HirBlockParameter, "type_id", 2) + f(abi.Vizg_HirBlockParameter, "origin_id", 3), vizg_c_fields_Vizg_HirBlockParameter());
    try std.testing.expectEqual(f(abi.Vizg_HirOriginDetail, "id", 1) + f(abi.Vizg_HirOriginDetail, "module_id", 2) + f(abi.Vizg_HirOriginDetail, "span_start", 3) + f(abi.Vizg_HirOriginDetail, "span_end", 4) + f(abi.Vizg_HirOriginDetail, "original_syntax", 5) + f(abi.Vizg_HirOriginDetail, "lowering_rule", 6) + f(abi.Vizg_HirOriginDetail, "type_id", 7) + f(abi.Vizg_HirOriginDetail, "parent_id", 8) + f(abi.Vizg_HirOriginDetail, "synthetic_reason", 9) + f(abi.Vizg_HirOriginDetail, "symbol_module_id", 10) + f(abi.Vizg_HirOriginDetail, "symbol_declaration_id", 11) + f(abi.Vizg_HirOriginDetail, "symbol_external", 12) + f(abi.Vizg_HirOriginDetail, "flags", 13) + f(abi.Vizg_HirOriginDetail, "reserved", 14), vizg_c_fields_Vizg_HirOriginDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirSemanticIdentity, "declaration_module_id", 1) + f(abi.Vizg_HirSemanticIdentity, "external_module_id", 2) + f(abi.Vizg_HirSemanticIdentity, "external_symbol_id", 3) + f(abi.Vizg_HirSemanticIdentity, "symbol_id", 4) + f(abi.Vizg_HirSemanticIdentity, "declaration_id", 5) + f(abi.Vizg_HirSemanticIdentity, "type_id", 6) + f(abi.Vizg_HirSemanticIdentity, "namespace_kind", 7) + f(abi.Vizg_HirSemanticIdentity, "declaration_external", 8) + f(abi.Vizg_HirSemanticIdentity, "has_host_binding_id", 9) + f(abi.Vizg_HirSemanticIdentity, "reserved", 10) + f(abi.Vizg_HirSemanticIdentity, "host_binding_id", 11), vizg_c_fields_Vizg_HirSemanticIdentity());
    try std.testing.expectEqual(f(abi.Vizg_HirModuleDetail, "module_id", 1) + f(abi.Vizg_HirModuleDetail, "initialization_function_id", 2) + f(abi.Vizg_HirModuleDetail, "dependency_count", 3) + f(abi.Vizg_HirModuleDetail, "import_count", 4) + f(abi.Vizg_HirModuleDetail, "export_count", 5), vizg_c_fields_Vizg_HirModuleDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirModuleDependency, "module_id", 1) + f(abi.Vizg_HirModuleDependency, "initialization_required", 2) + f(abi.Vizg_HirModuleDependency, "reserved", 3), vizg_c_fields_Vizg_HirModuleDependency());
    try std.testing.expectEqual(f(abi.Vizg_HirModuleImport, "local_binding_id", 1) + f(abi.Vizg_HirModuleImport, "source_id", 2) + f(abi.Vizg_HirModuleImport, "exported_name_ptr", 3) + f(abi.Vizg_HirModuleImport, "exported_name_len", 4) + f(abi.Vizg_HirModuleImport, "target", 5) + f(abi.Vizg_HirModuleImport, "source_kind", 6) + f(abi.Vizg_HirModuleImport, "type_only", 7) + f(abi.Vizg_HirModuleImport, "reserved", 8), vizg_c_fields_Vizg_HirModuleImport());
    try std.testing.expectEqual(f(abi.Vizg_HirModuleExport, "binding_id", 1) + f(abi.Vizg_HirModuleExport, "entity_id", 2) + f(abi.Vizg_HirModuleExport, "exported_name_ptr", 3) + f(abi.Vizg_HirModuleExport, "exported_name_len", 4) + f(abi.Vizg_HirModuleExport, "target", 5) + f(abi.Vizg_HirModuleExport, "type_only", 6) + f(abi.Vizg_HirModuleExport, "reserved", 7), vizg_c_fields_Vizg_HirModuleExport());
    try std.testing.expectEqual(f(abi.Vizg_HirBindingDetail, "id", 1) + f(abi.Vizg_HirBindingDetail, "declaration_id", 2) + f(abi.Vizg_HirBindingDetail, "initial_state", 3) + f(abi.Vizg_HirBindingDetail, "declaration_module_id", 4) + f(abi.Vizg_HirBindingDetail, "declaration_external", 5) + f(abi.Vizg_HirBindingDetail, "has_host_binding_id", 6) + f(abi.Vizg_HirBindingDetail, "reserved", 7) + f(abi.Vizg_HirBindingDetail, "host_binding_id", 8), vizg_c_fields_Vizg_HirBindingDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirFunctionStorageDetail, "id", 1) + f(abi.Vizg_HirFunctionStorageDetail, "capture_count", 2), vizg_c_fields_Vizg_HirFunctionStorageDetail());
    try std.testing.expectEqual(f(abi.Vizg_HirFunctionCapture, "local_binding_id", 1) + f(abi.Vizg_HirFunctionCapture, "source_binding_id", 2) + f(abi.Vizg_HirFunctionCapture, "source_kind", 3) + f(abi.Vizg_HirFunctionCapture, "mode", 4), vizg_c_fields_Vizg_HirFunctionCapture());
    try std.testing.expectEqual(f(abi.Vizg_HirRegionDetail, "id", 1) + f(abi.Vizg_HirRegionDetail, "function_id", 2) + f(abi.Vizg_HirRegionDetail, "parent_region_id", 3) + f(abi.Vizg_HirRegionDetail, "handler_block_id", 4) + f(abi.Vizg_HirRegionDetail, "continuation_block_id", 5) + f(abi.Vizg_HirRegionDetail, "origin_id", 6) + f(abi.Vizg_HirRegionDetail, "kind", 7) + f(abi.Vizg_HirRegionDetail, "protected_block_count", 8) + f(abi.Vizg_HirRegionDetail, "flags", 9) + f(abi.Vizg_HirRegionDetail, "reserved", 10), vizg_c_fields_Vizg_HirRegionDetail());

    try std.testing.expectEqual(@as(u32, @intFromEnum(abi.Vizg_ProjectStatus.INTERNAL_ERROR)), vizg_c_value_project_status_internal_error());
    try std.testing.expectEqual(@as(u32, @intFromEnum(abi.Vizg_LimitKind.SEMANTIC_GROWTH)), vizg_c_value_limit_semantic_growth());
    try std.testing.expectEqual(@as(u32, @intFromEnum(abi.Vizg_LimitKind.PARSE_DEPTH)), vizg_c_value_limit_parse_depth());
    try std.testing.expectEqual(@as(u32, 1), vizg_c_value_project_request_re_export());
    try std.testing.expectEqual(@as(u32, 11), vizg_c_value_external_type_object());
    try std.testing.expectEqual(abi.VIZG_EXTERNAL_NAMESPACE_VALUE, vizg_c_value_external_namespace_value());
    try std.testing.expectEqual(abi.VIZG_EXTERNAL_NAMESPACE_TYPE, vizg_c_value_external_namespace_type());
    try std.testing.expectEqual(abi.VIZG_EXTERNAL_NAMESPACE_BOTH, vizg_c_value_external_namespace_both());
    try std.testing.expectEqual(abi.VIZG_EXTERNAL_MODULE_API_VERSION, vizg_c_value_external_module_api_version());
    try std.testing.expectEqual(@as(u32, 3), vizg_c_value_external_declaration_type());
    try std.testing.expectEqual(abi.VIZG_EXTERNAL_EFFECT_UNKNOWN, vizg_c_value_external_effect_unknown());
}
